# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-25 13:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='no-avatar.jpg', upload_to='img/avatars/', verbose_name='Image'),
            preserve_default=False,
        ),
    ]
