# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-26 11:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='img/avatars/no-avatar.jpg', upload_to='img/avatars/', verbose_name='Image'),
        ),
    ]
