# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-25 10:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('tag_title', models.CharField(max_length=50)),
                ('tag_slug', models.CharField(max_length=200)),
            ],
            options={
                'abstract': False,
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='album',
            name='photos',
        ),
        migrations.AlterField(
            model_name='photo',
            name='source',
            field=models.ImageField(upload_to='img/galleries/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='taken_at',
            field=models.DateTimeField(),
        ),
        migrations.AddField(
            model_name='photo',
            name='tags',
            field=models.ManyToManyField(to='gallery.Tag'),
        ),
    ]
