# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-26 04:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_auto_20171126_0449'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='mime_type',
        ),
    ]
